% Calculate total CO2 sequestration, and HWP's CDS of this year.
function [total, hwpcds] = cal_total_cds(uncut, cut, planted, acc_hwp_cds)
    % uncut         Distribution of uncut tree's age
    % cut           Distribution of cut tree's age
    % planted       Distribution of planted tree's age
    % acc_hwp_cds   Total HWP CDS by the end of the last year
    % total         The total CDS by the end of this year
    % hwp_cds       HWP CDS generated by this year
    
    uncut_cnt = numel(uncut);
    cut_cnt = numel(cut);
    plant_cnt = numel(planted);
    
    total = 0;
    hwpcds = 0;
    
    % Accumulate the uncut trees' CDS
    for i = 1 : uncut_cnt
        [d, h] = growth_fun(uncut(i));
        total = total + tree_cds(d, h);
    end
    
    % Accumulate the hwps' CDS
    for i = 1 : cut_cnt
        [d, h] = growth_fun(cut(i));
        hwpcds = hwp_cds(d, h);
        total = total + hwpcds;
    end
    
    % Accumulate the newly planted trees' CDS
    for i = 1 : plant_cnt
        [d, h] = growth_fun(planted(i));
        total = total + tree_cds(d, h);
    end
    
    % Accumulate the total hwps' CDS before this year
    total = total + acc_hwp_cds;
end